#include "MitAna/DataTree/interface/Photon.h"

ClassImp(mithep::Photon)

namespace mithep {

  Photon::Photon() :
    fMom(),
    fCaloPos(),
    fR9(0.),
    fHadOverEm(0.),
    fHcalDepth1OverEcal(0.),
    fHcalDepth2OverEcal(0.),
    fMaxEnergyXtal(0.),
    fE15(0.),
    fE25(0.),
    fE33(0.),
    fE55(0.),
    fCovEtaEta(0.),
    fCoviEtaiEta(0.),
    fCoviEtaiEta5x5(0.),
    fEcalRecHitIso(0.),
    fHcalTowerSumEtDr04(0.),
    fHcalDepth1TowerSumEtDr04(0.),
    fHcalDepth2TowerSumEtDr04(0.),
    fSolidConeTrkIso(0.),
    fHollowConeTrkIso(0.),
    fSolidConeNTrk(0),
    fHollowConeNTrk(0),
    fEcalRecHitIsoDr03(0.),
    fHcalTowerSumEtDr03(0.),
    fHcalDepth1TowerSumEtDr03(0.),
    fHcalDepth2TowerSumEtDr03(0.),
    fSolidConeTrkIsoDr03(0.),
    fHollowConeTrkIsoDr03(0.),
    fSolidConeNTrkDr03(0),
    fHollowConeNTrkDr03(0),
    fPFChargedHadronIso(0.),
    fPFNeutralHadronIso(0.),
    fPFPhotonIso(0.),
    fHasPixelSeed(kFALSE),
    fIsEB(kFALSE),
    fIsEE(kFALSE),
    fIsEBGap(kFALSE),
    fIsEEGap(kFALSE),
    fIsEBEEGap(kFALSE),
    fIsLoosePhoton(kFALSE),
    fIsTightPhoton(kFALSE),
    fIsConverted(kFALSE),
    fSuperClusterRef(),
    fPVRef(),
    fEnergyErr(-99.),
    fEnergyErrSmeared(-99.),
    fEnergySmearing(0.),
    fEnergyRegr(0.),
    fEnergyErrRegr(0.),
    fEnergyPhoFix(0.),
    fEnergyErrPhoFix(0.),
    fVtxProb(1.0),
    fIdMva(-99.),
    fEtaWidth(-99.),
    fPhiWidth(-99.),
    fECALOnlySuperClusterRef(),
    fHadOverEmTow(0.),
    fHCalIsoTowDr03(0.),
    fHCalIsoTowDr04(0.),
    fConversionsD(),
    fConversionsS(),
    fPFPhotonsInMustache(),
    fPFPhotonsOutOfMustache(),
    fS4Ratio(-99.),
    fEffSigmaRR(-99.),
    fMipChi2(-999.),
    fMipTotEnergy(-999.),
    fMipSlope(-999.),
    fMipIntercept(-999.),
    fMipNHitCone(-1),
    fMipIsHalo(kFALSE),
    fMatchHePlusPos(0., 0., 0.),
    fMatchHePlusEn(-1.),
    fMatchHePlusTime(-1000.),
    fMatchHeMinusPos(0., 0., 0.),
    fMatchHeMinusEn(-1.),
    fMatchHeMinusTime(-1000.),
    fMatchHePlusPosDR15(0., 0., 0.),
    fMatchHePlusEnDR15(-1.),
    fMatchHePlusTimeDR15(-1000.),
    fMatchHeMinusPosDR15(0., 0., 0.),
    fMatchHeMinusEnDR15(-1.),
    fMatchHeMinusTimeDR15(-1000.),
    fEnergyErrSmearing(0.),
    fEnergyScale(1.)
  {
  }

  Photon::Photon(Double_t px, Double_t py, Double_t pz, Double_t e) :
    fMom(px, py, pz, e),
    fCaloPos(),
    fR9(0.),
    fHadOverEm(0.),
    fHcalDepth1OverEcal(0.),
    fHcalDepth2OverEcal(0.),
    fMaxEnergyXtal(0.),
    fE15(0.),
    fE25(0.),
    fE33(0.),
    fE55(0.),
    fCovEtaEta(0.),
    fCoviEtaiEta(0.),
    fCoviEtaiEta5x5(0.),
    fEcalRecHitIso(0.),
    fHcalTowerSumEtDr04(0.),
    fHcalDepth1TowerSumEtDr04(0.),
    fHcalDepth2TowerSumEtDr04(0.),
    fSolidConeTrkIso(0.),
    fHollowConeTrkIso(0.),
    fSolidConeNTrk(0),
    fHollowConeNTrk(0),
    fEcalRecHitIsoDr03(0.),
    fHcalTowerSumEtDr03(0.),
    fHcalDepth1TowerSumEtDr03(0.),
    fHcalDepth2TowerSumEtDr03(0.),
    fSolidConeTrkIsoDr03(0.),
    fHollowConeTrkIsoDr03(0.),
    fSolidConeNTrkDr03(0),
    fHollowConeNTrkDr03(0),
    fPFChargedHadronIso(0.),
    fPFNeutralHadronIso(0.),
    fPFPhotonIso(0.),
    fHasPixelSeed(kFALSE),
    fIsEB(kFALSE),
    fIsEE(kFALSE),
    fIsEBGap(kFALSE),
    fIsEEGap(kFALSE),
    fIsEBEEGap(kFALSE),
    fIsLoosePhoton(kFALSE),
    fIsTightPhoton(kFALSE),
    fIsConverted(kFALSE),
    fSuperClusterRef(),
    fPVRef(),
    fEnergyErr(-99.),
    fEnergyErrSmeared(-99.),
    fEnergySmearing(0.),
    fEnergyRegr(0.),
    fEnergyErrRegr(0.),
    fEnergyPhoFix(0.),
    fEnergyErrPhoFix(0.),
    fVtxProb(1.0),
    fIdMva(-99.),
    fEtaWidth(-99.),
    fPhiWidth(-99.),
    fECALOnlySuperClusterRef(),
    fHadOverEmTow(0.),
    fHCalIsoTowDr03(0.),
    fHCalIsoTowDr04(0.),
    fConversionsD(),
    fConversionsS(),
    fPFPhotonsInMustache(),
    fPFPhotonsOutOfMustache(),
    fS4Ratio(-99.),
    fEffSigmaRR(-99.),
    fMipChi2(-999.),
    fMipTotEnergy(-999.),
    fMipSlope(-999.),
    fMipIntercept(-999.),
    fMipNHitCone(-1),
    fMipIsHalo(kFALSE),
    fMatchHePlusPos(0., 0., 0.),
    fMatchHePlusEn(-1.),
    fMatchHePlusTime(-1000.),
    fMatchHeMinusPos(0., 0., 0.),
    fMatchHeMinusEn(-1.),
    fMatchHeMinusTime(-1000.),
    fMatchHePlusPosDR15(0., 0., 0.),
    fMatchHePlusEnDR15(-1.),
    fMatchHePlusTimeDR15(-1000.),
    fMatchHeMinusPosDR15(0., 0., 0.),
    fMatchHeMinusEnDR15(-1.),
    fMatchHeMinusTimeDR15(-1000.),
    fEnergyErrSmearing(0.),
    fEnergyScale(1.)
  {
  }

}
