from MitAna.TreeMod.bambu import mithep, analysis

trees = mithep.TreeContainer()
trees.AddFile("/scratch/dabercro/PUPPETSkims_JEC/skimPF.root")
trees.AddFile("/scratch/dabercro/PUPPETSkims_JEC/skimtreeMuon_JEC.root")
trees.AddFile("/scratch/dabercro/PUPPETSkims_JEC/skimtreenoMuon_JEC_jetPt20.root")
trees.AddFile("/scratch/dabercro/PUPPETSkims_JEC/skimtreenoMuon_JEC_jetPt30.root")
trees.AddFile("/scratch/dabercro/PUPPETSkims_JEC/skimtreenoMuon_JEC_ptFw_centralfx_0p0.root")
trees.AddFile("/scratch/dabercro/PUPPETSkims_JEC/skimtreenoMuon_JEC_ptFw_centralfx_1p0.root")
trees.AddFile("/scratch/dabercro/PUPPETSkims_JEC/skimtreenoMuon_JEC_ptFw_centralfx_1p5.root")
trees.AddFile("/scratch/dabercro/PUPPETSkims_JEC/skimtreenoMuon_JEC_ptFw_centralfx_2p0.root")
trees.AddFile("/scratch/dabercro/PUPPETSkims_JEC/skimtreenoMuon_JEC_ptFw_centralfx_2p5.root")
trees.AddFile("/scratch/dabercro/PUPPETSkims_JEC/skimtreenoMuon_JEC_ptFw_centralfx_3p0.root")
trees.AddFile("/scratch/dabercro/PUPPETSkims_JEC/skimtreenoMuon_JEC_ptFw_centralfx_4p0.root")
trees.AddFile("/scratch/dabercro/PUPPETSkims_JEC/skimtreenoMuon_JEC_ptFw_centralfx_5p0.root")

kGreen = 416

plotter = mithep.PlotResolution()
plotter.SetLineWidth(1)
plotter.SetLegendLimits(0.1,0.5,0.3,0.9)
plotter.SetTreeList(trees.ReturnTreeList("t"))
plotter.AddLegendEntry("PF",1)
plotter.AddLegendEntry("With Muon? JEC",2)
plotter.AddLegendEntry("Jet p_{T} > 20 GeV",4)
plotter.AddLegendEntry("Jet p_{T} > 30 GeV",6)
plotter.AddLegendEntry("0.0",kGreen+4)
plotter.AddLegendEntry("1.0",kGreen-1)
plotter.AddLegendEntry("1.5",kGreen+3)
plotter.AddLegendEntry("2.0",kGreen-2)
plotter.AddLegendEntry("2.5",kGreen+2)
plotter.AddLegendEntry("3.0",kGreen-3)
plotter.AddLegendEntry("4.0",kGreen+1)
plotter.AddLegendEntry("5.0",kGreen)
plotter.SetDefaultWeight("Boson_daughter==13 && Boson_Pt>30")

plotter.AddExprY("recoilPFMet_LongZ/-Boson_Pt")
plotter.AddExprY("recoilPFPuppiMet_LongZ/-Boson_Pt")
plotter.AddExprY("recoilPFPuppiMet_LongZ/-Boson_Pt")
plotter.AddExprY("recoilPFPuppiMet_LongZ/-Boson_Pt")
plotter.AddExprY("recoilPFPuppiMet_LongZ/-Boson_Pt")
plotter.AddExprY("recoilPFPuppiMet_LongZ/-Boson_Pt")
plotter.AddExprY("recoilPFPuppiMet_LongZ/-Boson_Pt")
plotter.AddExprY("recoilPFPuppiMet_LongZ/-Boson_Pt")
plotter.AddExprY("recoilPFPuppiMet_LongZ/-Boson_Pt")
plotter.AddExprY("recoilPFPuppiMet_LongZ/-Boson_Pt")
plotter.AddExprY("recoilPFPuppiMet_LongZ/-Boson_Pt")
plotter.AddExprY("recoilPFPuppiMet_LongZ/-Boson_Pt")

plotter.SetExprX("NVertex")
plotter.SetParameterLimits(1,0.5,1.5)
ResponseGraphsNPV = plotter.MakeFitGraphs(10,5,25,50,-3,3,1)

plotter.ResetExprY()
plotter.AddExprY("recoilPFMet_LongZ+Boson_Pt")
plotter.AddExprY("recoilPFPuppiMet_LongZ+Boson_Pt")
plotter.AddExprY("recoilPFPuppiMet_LongZ+Boson_Pt")
plotter.AddExprY("recoilPFPuppiMet_LongZ+Boson_Pt")
plotter.AddExprY("recoilPFPuppiMet_LongZ+Boson_Pt")
plotter.AddExprY("recoilPFPuppiMet_LongZ+Boson_Pt")
plotter.AddExprY("recoilPFPuppiMet_LongZ+Boson_Pt")
plotter.AddExprY("recoilPFPuppiMet_LongZ+Boson_Pt")
plotter.AddExprY("recoilPFPuppiMet_LongZ+Boson_Pt")
plotter.AddExprY("recoilPFPuppiMet_LongZ+Boson_Pt")
plotter.AddExprY("recoilPFPuppiMet_LongZ+Boson_Pt")
plotter.AddExprY("recoilPFPuppiMet_LongZ+Boson_Pt")

plotter.SetParameterLimits(1,-100,100)
ResolutionGraphsNPV = plotter.MakeFitGraphs(10,5,25,50,-100,100,2)

ResponseCanvasNPV = plotter.MakeCanvas(ResponseGraphsNPV,"Response","NPV","Response",0.5,2)
ResponseCanvasNPV.SaveAs("plots/NPVResponse.C")
ResponseCanvasNPV.SaveAs("plots/NPVResponse.pdf")
ResponseCanvasNPV.SaveAs("plots/NPVResponse.png")

ResolutionCanvasNPV = plotter.MakeCanvas(ResolutionGraphsNPV,"Resolution","NPV","Resolution [GeV]",10,40)
ResolutionCanvasNPV.SaveAs("plots/NPVResolution.C")
ResolutionCanvasNPV.SaveAs("plots/NPVResolution.pdf")
ResolutionCanvasNPV.SaveAs("plots/NPVResolution.png")

CorrectionGraphsNPV = plotter.GetRatioToLine(ResponseGraphsNPV,ResponseGraphsNPV[0])

CorrectedResolutionGraphsNPV = plotter.GetRatioToLines(ResolutionGraphsNPV,CorrectionGraphsNPV)
CorrectedResolutionCanvasNPV = plotter.MakeCanvas(CorrectedResolutionGraphsNPV,"Response-Corrected Resolution","NPV","Resolution [GeV]",10,40)
CorrectedResolutionCanvasNPV.SaveAs("plots/NPVCorrectedResolution.C")
CorrectedResolutionCanvasNPV.SaveAs("plots/NPVCorrectedResolution.pdf")
CorrectedResolutionCanvasNPV.SaveAs("plots/NPVCorrectedResolution.png")

ResolutionRatioGraphsNPV = plotter.GetRatioToPoint(CorrectedResolutionGraphsNPV,CorrectedResolutionGraphsNPV[0].GetY()[0])
ResolutionRatioCanvasNPV = plotter.MakeCanvas(ResolutionRatioGraphsNPV,"Response-Corrected Resolution Ratio","NPV","Ratio",0.5,3)
ResolutionRatioCanvasNPV.SaveAs("plots/NPVResolutionRatio.C")
ResolutionRatioCanvasNPV.SaveAs("plots/NPVResolutionRatio.pdf")
ResolutionRatioCanvasNPV.SaveAs("plots/NPVResolutionRatio.png")

##########################################################################
plotter.SetDefaultWeight("Boson_daughter==13")

plotter.ResetExprY()
plotter.AddExprY("recoilPFMet_LongZ/-Boson_Pt")
plotter.AddExprY("recoilPFPuppiMet_LongZ/-Boson_Pt")
plotter.AddExprY("recoilPFPuppiMet_LongZ/-Boson_Pt")
plotter.AddExprY("recoilPFPuppiMet_LongZ/-Boson_Pt")
plotter.AddExprY("recoilPFPuppiMet_LongZ/-Boson_Pt")
plotter.AddExprY("recoilPFPuppiMet_LongZ/-Boson_Pt")
plotter.AddExprY("recoilPFPuppiMet_LongZ/-Boson_Pt")
plotter.AddExprY("recoilPFPuppiMet_LongZ/-Boson_Pt")
plotter.AddExprY("recoilPFPuppiMet_LongZ/-Boson_Pt")
plotter.AddExprY("recoilPFPuppiMet_LongZ/-Boson_Pt")
plotter.AddExprY("recoilPFPuppiMet_LongZ/-Boson_Pt")
plotter.AddExprY("recoilPFPuppiMet_LongZ/-Boson_Pt")

plotter.SetExprX("Boson_Pt")
plotter.SetParameterLimits(1,0.5,1.1)
ResponseGraphsPT = plotter.MakeFitGraphs(10,0,200,50,-3,3,1)

plotter.ResetExprY()
plotter.AddExprY("recoilPFMet_LongZ+Boson_Pt")
plotter.AddExprY("recoilPFPuppiMet_LongZ+Boson_Pt")
plotter.AddExprY("recoilPFPuppiMet_LongZ+Boson_Pt")
plotter.AddExprY("recoilPFPuppiMet_LongZ+Boson_Pt")
plotter.AddExprY("recoilPFPuppiMet_LongZ+Boson_Pt")
plotter.AddExprY("recoilPFPuppiMet_LongZ+Boson_Pt")
plotter.AddExprY("recoilPFPuppiMet_LongZ+Boson_Pt")
plotter.AddExprY("recoilPFPuppiMet_LongZ+Boson_Pt")
plotter.AddExprY("recoilPFPuppiMet_LongZ+Boson_Pt")
plotter.AddExprY("recoilPFPuppiMet_LongZ+Boson_Pt")
plotter.AddExprY("recoilPFPuppiMet_LongZ+Boson_Pt")
plotter.AddExprY("recoilPFPuppiMet_LongZ+Boson_Pt")

plotter.SetParameterLimits(1,-100,100)
ResolutionGraphsPT = plotter.MakeFitGraphs(10,0,200,50,-100,100,2)

ResponseCanvasPT = plotter.MakeCanvas(ResponseGraphsPT,"Response","Boson p_{T} [GeV]","Response",0.5,2)
ResponseCanvasPT.SaveAs("plots/PTResponse.C")
ResponseCanvasPT.SaveAs("plots/PTResponse.pdf")
ResponseCanvasPT.SaveAs("plots/PTResponse.png")

ResolutionCanvasPT = plotter.MakeCanvas(ResolutionGraphsPT,"Resolution","Boson p_{T} [GeV]","Resolution [GeV]",10,50)
ResolutionCanvasPT.SaveAs("plots/PTResolution.C")
ResolutionCanvasPT.SaveAs("plots/PTResolution.pdf")
ResolutionCanvasPT.SaveAs("plots/PTResolution.png")

CorrectionGraphsPT = plotter.GetRatioToLine(ResponseGraphsPT,ResponseGraphsPT[0])

CorrectedResolutionGraphsPT = plotter.GetRatioToLines(ResolutionGraphsPT,CorrectionGraphsPT)
CorrectedResolutionCanvasPT = plotter.MakeCanvas(CorrectedResolutionGraphsPT,"Response-Corrected Resolution","Boson p_{T} [GeV]","Resolution [GeV]",10,50)
CorrectedResolutionCanvasPT.SaveAs("plots/PTCorrectedResolution.C")
CorrectedResolutionCanvasPT.SaveAs("plots/PTCorrectedResolution.pdf")
CorrectedResolutionCanvasPT.SaveAs("plots/PTCorrectedResolution.png")

ResolutionRatioGraphsPT = plotter.GetRatioToPoint(CorrectedResolutionGraphsPT,CorrectedResolutionGraphsPT[0].GetY()[0])
ResolutionRatioCanvasPT = plotter.MakeCanvas(ResolutionRatioGraphsPT,"Response-Corrected Resolution Ratio","Boson p_{T} [GeV]","Ratio",0.5,3)
ResolutionRatioCanvasPT.SaveAs("plots/PTResolutionRatio.C")
ResolutionRatioCanvasPT.SaveAs("plots/PTResolutionRatio.pdf")
ResolutionRatioCanvasPT.SaveAs("plots/PTResolutionRatio.png")

del plotter
del trees
